chore: update file structure to ensure clean testing environments for comparing outputs, separating current and legacy libraries, and isolating protocol files

diff --git a/Proverif-Case-Studies/MDH_construct/Makefile b/Proverif-Case-Studies/MDH_construct/Makefile
--- a/Proverif-Case-Studies/MDH_construct/Makefile
+++ b/Proverif-Case-Studies/MDH_construct/Makefile
@@ -1,3 +1,7 @@
+ROOT = Protocols
+LIB_SET ?= current
+LIB_ROOT = libs/$(LIB_SET)
+
 ifdef ike
   FOLDER = NDSS_ikeV2_HF_EC
 endif
@@ -7,20 +11,38 @@ ifdef ike_s
 endif
 
 ifdef sigma
-  FOLDER="sigma_HF_EC"
+  FOLDER = sigma_HF_EC
+endif
+
+ifdef universal
+  FOLDER = Universal_Protocol_Test
+endif
+
+ifdef protosuite
+  FOLDER = Protocol_Models_Adapted
 endif
 
 ifdef col
   EXT=collision
-  LIB=-lib hash_no_collision.pvl -lib hash_collision.pvl
+	LIB=-lib $(LIB_ROOT)/hash_no_collision.pvl -lib $(LIB_ROOT)/hash_collision.pvl
 else
 EXT=no_collision
 ifdef assoc
-  LIB=-lib assoc_no_collision.pvl
+	LIB=-lib $(LIB_ROOT)/assoc_no_collision.pvl
 else
-  LIB=-lib hash_no_collision.pvl
+	LIB=-lib $(LIB_ROOT)/hash_no_collision.pvl
 endif
 endif
 
 all:
-	proverif $(LIB) -lib isCol.pvl -lib $(FOLDER)/$(FOLDER)_declaration.pvl $(FOLDER)/$(FOLDER)_$(EXT).pv
+	@if [ "$(FOLDER)" = "Protocol_Models_Adapted" ]; then \
+	  if [ -z "$(MODEL)" ]; then \
+	    echo "Error: set MODEL=<file.pv> when using protosuite=1"; \
+	    exit 1; \
+	  fi; \
+	  proverif $(LIB) -lib $(LIB_ROOT)/isCol.pvl $(ROOT)/$(FOLDER)/$(MODEL); \
+	elif [ "$(FOLDER)" = "Universal_Protocol_Test" ]; then \
+	  proverif $(LIB) -lib $(LIB_ROOT)/isCol.pvl $(ROOT)/$(FOLDER)/universal_protocol.pv; \
+	else \
+	  proverif $(LIB) -lib $(LIB_ROOT)/isCol.pvl -lib $(ROOT)/$(FOLDER)/$(FOLDER)_declaration.pvl $(ROOT)/$(FOLDER)/$(FOLDER)_$(EXT).pv; \
+	fi
